Quote pre-build command and arguments
c-smile/sciter-js-sdk pull request #256
Opened 2022-01-06 19:42 UTC by BilyakA

This fixes windows build in case `$(ProjectDir)` contains white spaces

2022-01-06 21:33 UTC, c-smile requested changes
These projects are generated by premake5 so changing .vcxproj files is useless.

Instead, they should be fixed in the premake script here:
https://github.com/c-smile/sciter-js-sdk/blob/main/premake5.lua#L147

and in other three places in that script.

2022-02-16 06:18 UTC, 8ctopus commented
@BilyakA do it the right way or close the PR.

2022-02-18 15:37 UTC, BilyakA commented
Changed `premake5.lua` but I am not sure which command is used to generate makefiles / projects / solutions from it (especially wich version of Visual Studio projects are generated and included in the repo by default).

2022-02-21 13:43 UTC, 8ctopus commented
probably not a smart idea to force push when making pull requests ;)

2022-02-26 16:52 UTC, merged